name: compile shaders

on:
  pull_request:
    branches:
      - dev
  workflow_call:

jobs:
  compile-shaders:
    runs-on: windows-latest
    name: compile shaders
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: setup SPIRV tools
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.204.0
          vulkan-components: Glslang, SPIRV-Cross
          vulkan-use-cache: true
      
      - name: install DXC
        uses: napokue/setup-dxc@v1.0.0

      - name: run shader compilers
        run: ninja
        working-directory: piet-gpu/shader
